name: action-semantic-release
description: action-semantic-relase
inputs:
  token:
    description: "The github secret token"
    required: true
runs:
  using: "composite"
  steps:
    - uses: go-semantic-release/action@v1
      env:
        github-token: ${{ inputs.token }}

