name: semantic-release-action
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_call:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Validate PR title
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: ./.github/actions/semantic-pull-request
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/semantic-release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
