name: semantic-release-action
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  workflow_call:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Validate PR title
        if: ${{ github.ref != 'refs/heads/main' }}
        uses: mondo192/semantic-release-action/.github/actions/semantic-pull-request@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Semantic release
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: mondo192/semantic-release-action/.github/actions/semantic-release@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
